Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
a=int(input())
x = np.arange(a+1)[::-1]#добавила +1, чтобы выводилось с того числа, которое ввели
x

15


array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
b=int(input())

b_diag=np.diag(np.arange(b+1)[::-1])#добавила +1, чтобы выводилось с того числа, которое ввели
b_diag_sum = 0
for i in range(0, b):
    b_diag_sum += b_diag[i][i]
print(b_diag_sum)

7
28


Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [4]:
from numpy import linalg

In [5]:
l = np.array( [ [4, 2,1], [1, 3,0],[0,5,4] ] )
r = np.array( [4, 12,-3] )
linalg.solve(l, r)

array([ 0.46666667,  3.84444444, -5.55555556])

In [6]:
np.allclose( np.dot(l, linalg.solve(l, r)), r )

True

Задача 4 домашнего задания

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [7]:
#Матрица
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [8]:
#На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [9]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [11]:
#Найдите самого похожего пользователя. 
#Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats
a=[]
for i in range(10):
    a.append(cosine(users_stats[i],next_user_stats))
print(a.index(max(a)))
print(a)

7
[0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0]


In [17]:
#косинус с максимально похожим 0.9486832980505, 8й пользователь
users_stats[7]

array([0, 1, 1, 0, 0, 0])

In [15]:
print(next_user_stats)

[0 1 2 0 0 0]
